replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
  -regcred


  service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: "ngnix"
  annotations: {}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns01
    acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: dev-artemis.tatianatech.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - secretName: dev-artemis-tls
      hosts:
        - dev-artemis.tatianatech.com